/*
* generated by Xtext
*/
package org;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MiniGobstonesStandaloneSetup extends MiniGobstonesStandaloneSetupGenerated{

	public static void doSetup() {
		new MiniGobstonesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

