/**
 * generated by Xtext
 */
package org.validation;

import org.validation.AbstractMiniGobstonesValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MiniGobstonesValidator extends AbstractMiniGobstonesValidator {
}
