/**
 * generated by Xtext
 */
package org.generator;

import com.google.common.base.Objects;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.miniGobstones.Color;
import org.miniGobstones.Command;
import org.miniGobstones.Direccion;
import org.miniGobstones.Model;
import org.miniGobstones.Mover;
import org.miniGobstones.Poner;
import org.miniGobstones.Procedure;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class MiniGobstonesGenerator implements IGenerator {
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    String _className = this.className(resource);
    String _plus = (_className + ".java");
    CharSequence _javaCode = this.toJavaCode(resource);
    fsa.generateFile(_plus, _javaCode);
  }
  
  public String className(final Resource res) {
    URI _uRI = res.getURI();
    String name = _uRI.lastSegment();
    int _indexOf = name.indexOf(".");
    return name.substring(0, _indexOf);
  }
  
  public CharSequence toJavaCode(final Resource res) {
    CharSequence _xblockexpression = null;
    {
      EList<EObject> _contents = res.getContents();
      EObject _head = IterableExtensions.<EObject>head(_contents);
      Model model = ((Model) _head);
      CharSequence _javaCode = this.toJavaCode(model);
      _xblockexpression = (_javaCode);
    }
    return _xblockexpression;
  }
  
  public CharSequence toJavaCode(final Model model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("import enums.Color;");
    _builder.newLine();
    _builder.append("import enums.Direccion;\t\t\t");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class ");
    Resource _eResource = model.eResource();
    String _className = this.className(_eResource);
    _builder.append(_className, "");
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("public static void main(String[] args) {\t");
    _builder.newLine();
    _builder.append("\t\t");
    CharSequence _compile = this.compile(model);
    _builder.append(_compile, "		");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compile(final Model model) {
    StringConcatenation _builder = new StringConcatenation();
    {
      Procedure _main = model.getMain();
      EList<Command> _commands = _main.getCommands();
      for(final Command command : _commands) {
        String _compile = this.compile(command);
        _builder.append(_compile, "");
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder;
  }
  
  public String compile(final Command command) {
    String _xifexpression = null;
    EClass _eClass = command.eClass();
    String _name = _eClass.getName();
    boolean _equals = Objects.equal(_name, "Poner");
    if (_equals) {
      Poner comm = ((Poner) command);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Cabezal.getInstace().poner(");
      Color _color = comm.getColor();
      _builder.append(_color, "");
      _builder.append(")");
      return _builder.toString();
    } else {
      String _xifexpression_1 = null;
      EClass _eClass_1 = command.eClass();
      String _name_1 = _eClass_1.getName();
      boolean _equals_1 = Objects.equal(_name_1, "Mover");
      if (_equals_1) {
        Mover comm_1 = ((Mover) command);
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.append("Cabezal.getInstance().mover(");
        Direccion _dir = comm_1.getDir();
        _builder_1.append(_dir, "");
        _builder_1.append(")");
        return _builder_1.toString();
      }
      _xifexpression = _xifexpression_1;
    }
    return _xifexpression;
  }
}
