/*
 * generated by Xtext
 */
package org.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MiniGobstonesUiModule extends org.ui.AbstractMiniGobstonesUiModule {
	public MiniGobstonesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
