/*
* generated by Xtext
*/
package org.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.services.MiniGobstonesGrammarAccess;

public class MiniGobstonesParser extends AbstractContentAssistParser {
	
	@Inject
	private MiniGobstonesGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.ui.contentassist.antlr.internal.InternalMiniGobstonesParser createParser() {
		org.ui.contentassist.antlr.internal.InternalMiniGobstonesParser result = new org.ui.contentassist.antlr.internal.InternalMiniGobstonesParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getCommandAccess().getAlternatives(), "rule__Command__Alternatives");
					put(grammarAccess.getColorAccess().getAlternatives(), "rule__Color__Alternatives");
					put(grammarAccess.getDireccionAccess().getAlternatives(), "rule__Direccion__Alternatives");
					put(grammarAccess.getProcedureAccess().getGroup(), "rule__Procedure__Group__0");
					put(grammarAccess.getPonerAccess().getGroup(), "rule__Poner__Group__0");
					put(grammarAccess.getMoverAccess().getGroup(), "rule__Mover__Group__0");
					put(grammarAccess.getModelAccess().getMainAssignment(), "rule__Model__MainAssignment");
					put(grammarAccess.getProcedureAccess().getNameAssignment_1(), "rule__Procedure__NameAssignment_1");
					put(grammarAccess.getProcedureAccess().getCommandsAssignment_3(), "rule__Procedure__CommandsAssignment_3");
					put(grammarAccess.getPonerAccess().getColorAssignment_3(), "rule__Poner__ColorAssignment_3");
					put(grammarAccess.getMoverAccess().getDirAssignment_3(), "rule__Mover__DirAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.ui.contentassist.antlr.internal.InternalMiniGobstonesParser typedParser = (org.ui.contentassist.antlr.internal.InternalMiniGobstonesParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MiniGobstonesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MiniGobstonesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
