/*
* generated by Xtext
*/
package org;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MiniGobstonesUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.ui.internal.MiniGobstonesActivator.getInstance().getInjector("org.MiniGobstones");
	}
	
}
