/*
* generated by Xtext
*/
package org.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.services.MiniGobstonesGrammarAccess;

public class MiniGobstonesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MiniGobstonesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.parser.antlr.internal.InternalMiniGobstonesParser createParser(XtextTokenStream stream) {
		return new org.parser.antlr.internal.InternalMiniGobstonesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public MiniGobstonesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MiniGobstonesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
