/*
 * generated by Xtext
 */
package org.ui.contentassist

import org.ui.contentassist.AbstractMiniGobstonesProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MiniGobstonesProposalProvider extends AbstractMiniGobstonesProposalProvider {
}
